// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-2JG5ZzZug6uuII8_bJIcu8sG-ZokN8',
    appId: '1:853469777982:web:8a81ce122ab5601a5d416f',
    messagingSenderId: '853469777982',
    projectId: 'myapp-addcd',
    authDomain: 'myapp-addcd.firebaseapp.com',
    storageBucket: 'myapp-addcd.appspot.com',
    measurementId: 'G-3HVL7N6CG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_OBwyjVA8Sl_1qfNSuPOisWj-h1XC93k',
    appId: '1:853469777982:android:5f42a11e31f7b25b5d416f',
    messagingSenderId: '853469777982',
    projectId: 'myapp-addcd',
    storageBucket: 'myapp-addcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTbJXyXAtpkI85uUTLGCGBr-d2WXBYZc',
    appId: '1:853469777982:ios:8e1849cabab11ec75d416f',
    messagingSenderId: '853469777982',
    projectId: 'myapp-addcd',
    storageBucket: 'myapp-addcd.appspot.com',
    iosClientId:
        '853469777982-g6bp6to87ullinl1jqtt2v12b82ha9ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTbJXyXAtpkI85uUTLGCGBr-d2WXBYZc',
    appId: '1:853469777982:ios:335fc5dea976681d5d416f',
    messagingSenderId: '853469777982',
    projectId: 'myapp-addcd',
    storageBucket: 'myapp-addcd.appspot.com',
    iosClientId:
        '853469777982-ir72mjedcfkeq1rdf6efd84av6h174h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
